[package]
name = "vanity-bitcoin-address-generator"
version = "0.1.0"
authors = ["mhkafadar"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faster-hex = "0.5.0"
rust-crypto = "0.2.36"
